{% set name = "junifer" %}
{% set version = "0.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/junifer-{{ version }}.tar.gz
  sha256: 319c997bec8d4b093cbcf8d005277feb089c642d627d3dc86d8b4fdc09652ccb

build:
  noarch: python
  entry_points:
    - junifer = junifer.api.cli:cli
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=64
    - setuptools-scm >=8
    - pip
  run:
    - python >=3.8
    - click >=8.1.3,<8.2
    - numpy >=1.24,<1.27
    - scipy >=1.9.0,<=1.11.4
    - datalad >=0.15.4,<0.20
    - pandas >=1.4.0,<2.2
    - nibabel >=3.2.0,<5.11
    - nilearn >=0.9.0,<=0.10.2
    - sqlalchemy >=1.4.27,<=2.1.0
    - ruamel.yaml >=0.17,<0.18
    - h5py >=3.10
    - httpx[http2] ==0.26.0
    - tqdm ==4.66.1
    - templateflow >=23.0.0
    - importlib-metadata
    - looseversion ==1.3.0
    - bctpy >=0.6.0,<0.7.0
    - neurokit2 >=0.1.7

test:
  imports:
    - junifer
  commands:
    - pip check
    - junifer --help
  requires:
    - pip

about:
  home: https://github.com/juaml/junifer
  summary: JUelich NeuroImaging FEature extractoR
  license: AGPL-3.0-only
  license_file: LICENSE.md
  doc_url: https://juaml.github.io/junifer/main/index.html
  dev_url: https://github.com/juaml/junifer

extra:
  recipe-maintainers:
    - synchon
